baseurl = "http://www.sagarayi.github.io" # Hostname (and path) to the root.
title = "sagarayi" # Site title.
theme = "coder" # Set the theme.
languagecode = "en" # The siteâ€™s language code.

paginate = 20 # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

[params] # theme parameters
    author = "Sagar Ayi" # Author's name.
    
    description = "Sagar Ayi's personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.

    disqusShortname = "sagarayi" # Enable or disable Disqus

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
	custom_css = []

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/sagarayi/"
[[params.social]]
    name = "Youtube"
    weight = 2
    url = "https://www.youtube.com/user/MrSagarayi/"
[[params.social]]
    name = "Quora"
    weight = 3
    url = "https://www.quora.com/profile/Sagar-Ayi"
[[params.social]]
    name = "Resume"
    weight = 4
    url = "https://drive.google.com/file/d/14eU4SDiiEhPDOclu845n0u302mtebItA/view?usp=sharing"    

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"